import { useEffect, useRef, useState } from 'react'
import { exploring, experiments, journey, leadership, projects, skills, socialLinks } from './data'
import './App.css'

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [scrolled, setScrolled] = useState(false)
  const [activeProject, setActiveProject] = useState<number | null>(null)
  const [music, setMusic] = useState(true)
  const [sent, setSent] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [submitError, setSubmitError] = useState('')
  const [cgpi, setCgpi] = useState(0)
  const audioRef = useRef<HTMLAudioElement>(null)
  const [cursor, setCursor] = useState({ x: -100, y: -100, label: '' })
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 24); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll) }, [])
  useEffect(() => { const items = document.querySelectorAll('.animate-in'); const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) entry.target.classList.add('is-visible') }), { threshold: .12 }); items.forEach(item => observer.observe(item)); return () => observer.disconnect() }, [])
  useEffect(() => { const metric = document.querySelector('.cgpi-value'); if (!metric) return; const observer = new IntersectionObserver(entries => { if (!entries[0].isIntersecting) return; let value = 0; const timer = window.setInterval(() => { value = Math.min(9.91, value + .17); setCgpi(Number(value.toFixed(2))); if (value >= 9.91) window.clearInterval(timer) }, 35); observer.disconnect() }, { threshold: .5 }); observer.observe(metric); return () => observer.disconnect() }, [])
  useEffect(() => { const onMove = (event: MouseEvent) => setCursor({ x: event.clientX, y: event.clientY, label: (event.target as HTMLElement).closest('a,button,.project,.node')?.getAttribute('data-cursor') || '' }); window.addEventListener('mousemove', onMove); return () => window.removeEventListener('mousemove', onMove) }, [])
  const toggleMusic = () => { if (!audioRef.current) return; if (music) { audioRef.current.muted = true; audioRef.current.pause(); setMusic(false) } else { audioRef.current.muted = false; audioRef.current.play().catch(() => undefined); setMusic(true) } }
  const submitContactForm = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    setSubmitting(true)
    setSubmitError('')
    try {
      const response = await fetch('https://formspree.io/f/mgaewnyq', { method: 'POST', body: new FormData(event.currentTarget), headers: { Accept: 'application/json' } })
      if (!response.ok) throw new Error('Unable to deliver message')
      setSent(true)
      event.currentTarget.reset()
    } catch {
      setSubmitError('Something went wrong while sending. Please try again or email me directly.')
    } finally { setSubmitting(false) }
  }
  return <div className="site-shell">
    <audio ref={audioRef} src="/audio/portfolio_bgm.mp3" autoPlay muted loop preload="none" aria-label="Ambient background music" />
    <div className={`custom-cursor ${cursor.label ? 'cursor-active' : ''}`} style={{ left: cursor.x, top: cursor.y }} aria-hidden="true"><span>{cursor.label || '·'}</span></div>
    <header className={scrolled ? 'nav scrolled' : 'nav'}><a className="logo" href="#top" data-cursor="TOP" aria-label="Back to top" title="Back to top">SD<span>.</span></a><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? 'CLOSE' : 'MENU'}</button><nav className={menuOpen ? 'nav-links open' : 'nav-links'}>{['about', 'work', 'exploring', 'leadership', 'journey', 'contact'].map(item => <a key={item} href={`#${item}`} onClick={() => setMenuOpen(false)}>{item}</a>)}<a className="nav-resume" href="/resume.pdf" download="Souvik-Dutta-Resume.pdf" data-cursor="DOWNLOAD">RESUME <span>↓</span></a></nav><button className={music ? 'ambient active' : 'ambient'} onClick={toggleMusic} data-cursor="SOUND" aria-label="Toggle ambient music"><i /> AMBIENT {music ? 'ON' : 'OFF'}</button></header>
    <main id="top">
      <section className="hero"><div className="hero-grid" aria-hidden="true" /><div className="hero-orbit orbit-one" aria-hidden="true" /><div className="hero-orbit orbit-two" aria-hidden="true" /><div className="hero-content"><div className="identity reveal"><img
  className="portrait-slot"  src="/pfp.jpg"  alt="Souvik Dutta"/><div><p className="eyebrow">SOFTWARE DEVELOPER <span>•</span> AI ENTHUSIAST</p><p className="identity-name">Souvik Dutta</p></div></div><h1 className="reveal delay-one">I build software,<br /><em>explore AI,</em> and bring<br />people together.</h1><p className="hero-note reveal delay-two">A Computer Science student turning curiosity into working systems, useful tools, and shared momentum.</p><div className="hero-actions reveal delay-two"><a className="button button-fill" href="#work" data-cursor="EXPLORE">Explore my work <span>↘</span></a><a className="button button-line" href="#contact" data-cursor="CONNECT">Let's connect <span>↗</span></a><a className="button button-resume" href="/resume.pdf" download="Souvik-Dutta-Resume.pdf" data-cursor="DOWNLOAD" aria-label="Download Souvik Dutta's resume">Download resume <span aria-hidden="true">↓</span></a></div></div><div className="hero-side"><span>01 / 06</span><span className="vertical-label">PORTFOLIO · 2026</span></div><div className="scroll-cue">SCROLL TO EXPLORE <span>↓</span></div></section>
      <section id="about" className="section about-section"><div className="section-intro"><span className="section-index">01 — ABOUT</span><h2>More than<br /><em>just code.</em></h2></div><div className="about-copy"><p className="lead">I enjoy turning ideas into working software, exploring emerging technologies, and creating environments where other people can learn and build too.</p><div className="pillars">{[['01','BUILD','Software projects, AI applications, APIs, full-stack systems, automation, IoT, and developer tools.'],['02','EXPLORE','Generative AI, LLM applications, Agentic AI, tool calling, context engineering, RAG, CAG, and what comes next.'],['03','LEAD','Technology communities, technical events, workshops, student teams, and opportunities to participate.']].map(([num,title,text]) => <div key={title}><b>{num}</b><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
      <section id="work" className="section work-section"><div className="section-intro work-heading"><span className="section-index">02 — SELECTED WORK</span><h2>Things I've<br /><em>built.</em></h2><p>Ideas become interesting when they become software.</p></div><div className="project-list">{projects.map((project, index) => <article className={`project project-${project.accent} animate-in`} data-cursor="VIEW" key={project.title} onClick={() => setActiveProject(index)} onKeyDown={event => { if (event.key === 'Enter') setActiveProject(index) }} role="button" tabIndex={0}><div className="project-art"><span className="project-number">{project.number}</span><div className="art-lines" /><strong>{project.title.split(' ').slice(0, 2).join(' ')}<br /><i>{project.title.split(' ').slice(2).join(' ')}</i></strong><span className="view-project">VIEW <b>↗</b></span></div><div className="project-info"><span className="tag">{project.type}</span><h3>{project.title}</h3><p>{project.description}</p><div className="tech-row">{project.tech.map(tech => <span key={tech}>{tech}</span>)}</div><button className="text-link">OPEN CASE STUDY <span>↗</span></button></div></article>)}</div><div className="experiments"><span className="section-index">MORE EXPERIMENTS</span><div>{experiments.map(experiment => <span key={experiment}>{experiment} <b>↗</b></span>)}</div></div></section>
      <section id="exploring" className="section explore-section"><div className="section-intro"><span className="section-index">03 — CURRENTLY EXPLORING</span><h2>Where I'm<br /><em>going next.</em></h2><p>Technology moves quickly. I like learning by building.</p></div><div className="constellation">{exploring.map(([label, ...items]) => <div className="constellation-row" key={label}><span className="constellation-label">{label}</span><div>{items.map(item => <span className="node" key={item}>{item}<small>↗</small></span>)}</div></div>)}</div></section>
      <section className="section skills-section"><div className="section-intro"><span className="section-index">04 — TOOLKIT</span><h2>Curious by<br /><em>default.</em></h2></div><div className="skills-grid">{Object.entries(skills).map(([group, items]) => <div className="skill-group" key={group}><h3>{group}</h3><div>{items.map(item => <span key={item}>{item}</span>)}</div></div>)}</div></section>
      <section id="leadership" className="section leadership-section"><div className="section-intro"><span className="section-index">05 — COMMUNITY</span><h2>Building the<br /><em>tech community.</em></h2><p>Technology becomes more meaningful when people build and learn together.</p></div><div className="leadership-content"><div className="leadership-map animate-in"><span className="map-line" />{['TechKshetra', 'CSI', 'GFG', 'Students Council'].map((node, index) => <div className="map-node" key={node}><b>0{index + 1}</b>{node}</div>)}</div><div className="leadership-list">{leadership.map(([title, role, detail]) => <div className="leadership-item animate-in" key={title}><span>{title}</span><h3>{role}</h3><p>{detail}</p></div>)}</div></div><div className="gallery-placeholder"><span>EVENTS / WORKSHOPS / PEOPLE</span><b>Space reserved for<br />the moments that<br />make the work matter.</b><i>+</i></div></section>
      <section id="journey" className="section journey-section"><div className="section-intro"><span className="section-index">06 — THE JOURNEY</span><h2>Still becoming<br /><em>the engineer.</em></h2></div><div className="journey-list">{journey.map(([date, type, title, detail]) => <div className="journey-item animate-in" key={title}><span className="date">{date}</span><span className="type">{type}</span><div><h3>{title}</h3><p>{detail}</p></div></div>)}</div></section>
      <section id="education" className="education-section" aria-labelledby="education-title"><div className="education-header"><span className="section-index">07 — ACADEMIC JOURNEY / 2024 — PRESENT</span><h2 id="education-title">Education<span>.</span></h2><p>Building the academic foundation behind my work in computer science and technology.</p></div><div className="education-timeline"><div className="timeline-progress" aria-hidden="true" /><article className="education-entry current animate-in"><div className="timeline-marker"><span>2024—27</span><i /></div><div className="education-card"><div className="education-card-copy"><span className="education-status">CURRENT DEGREE</span><h3>B.K. Birla College, Kalyan</h3><p className="education-degree">Bachelor's degree in Computer Science</p><p className="education-duration">2024 — 2027</p><p className="education-description">Building a broad foundation across software, systems, and emerging technology.</p></div><div className="metric-block"><strong className="cgpi-value" aria-label={`CGPI ${cgpi.toFixed(2)}`}>{cgpi.toFixed(2)}</strong><span>CGPI</span></div></div></article><article className="education-entry animate-in"><div className="timeline-marker"><span>2022—24</span><i /></div><div className="education-card"><div className="education-card-copy"><span className="education-status">COMPLETED</span><h3>Model College, Thakurli</h3><p className="education-degree">HSC</p><p className="education-duration">2022 — 2024</p><p className="education-description">A completed higher-secondary foundation before beginning my computer science degree.</p></div><div className="metric-block secondary"><strong>80.50%</strong><span>GRADE</span></div></div></article></div></section>
      <section id="contact" className="contact-section"><div className="contact-heading"><span className="section-index">07 — CONTACT</span><h2>Have an idea<br />worth <em>building?</em></h2><p>I'm interested in interesting problems, ambitious projects, technology collaborations, and opportunities to learn and build.</p><div className="contact-links"><a href={socialLinks.github} target="_blank">GitHub ↗</a><a href={socialLinks.linkedin} target="_blank">LinkedIn ↗</a><a href={socialLinks.email}>Email ↗</a></div></div><form onSubmit={submitContactForm}>{sent ? <div className="success"><div className="success-mark" aria-hidden="true"><span /></div><h3>Message delivered.</h3><p>Thanks for reaching out. I'll get back to you soon.</p><div className="success-line" /></div> : <><label>Name<input required name="name" placeholder="Your name" /></label><label>Email<input required type="email" name="email" placeholder="you@example.com" /></label><label>Message<textarea required name="message" placeholder="Tell me what you're building..." rows={4} /></label>{submitError && <p className="form-error" role="alert">{submitError}</p>}<button className="button button-fill" type="submit" disabled={submitting}>{submitting ? 'Sending...' : 'Start a conversation'} <span>{submitting ? '…' : '↗'}</span></button></>}</form></section>
    </main>
    <footer><div><a className="logo" href="#top">SD<span>.</span></a><p>Software Developer · AI Enthusiast · Technology Community Leader</p></div><div className="footer-links"><a href={socialLinks.github}>GitHub</a><a href={socialLinks.linkedin}>LinkedIn</a><a href={socialLinks.email}>Email</a><a href="/resume.pdf" download="Souvik-Dutta-Resume.pdf">Resume</a></div><small>© 2026 Souvik Dutta · Built with curiosity.</small></footer>
    {activeProject !== null && <div className="modal-backdrop" onClick={() => setActiveProject(null)}><div className="project-modal" onClick={event => event.stopPropagation()}><button className="modal-close" onClick={() => setActiveProject(null)}>CLOSE ×</button><span className="tag">{projects[activeProject].type}</span><h2>{projects[activeProject].title}</h2><p>{projects[activeProject].detail}</p><div className="tech-row">{projects[activeProject].tech.map(tech => <span key={tech}>{tech}</span>)}</div><a className="text-link" href={projects[activeProject].github} target="_blank">VIEW ON GITHUB ↗</a></div></div>}
  </div>
}
export default App
