export const projects = [
  { number: '01', title: 'YouTube Video Summarizer', type: 'AI / NLP', description: 'An end-to-end application that turns long-form video into clear, useful knowledge.', detail: 'Extracts audio, transcribes speech, and creates intelligent summaries through an interactive Gradio interface.', tech: ['Python', 'OpenAI Whisper', 'Transformers', 'Gradio'], github: 'https://github.com/s7d4007/Youtube_Summarizer', accent: 'lime' },
  { number: '02', title: 'AgriSahayak', type: 'SMART AGRICULTURE', description: 'Agricultural intelligence designed to make machine learning more useful at the farm level.', detail: 'Plant disease detection, multilingual support, and API-powered insights brought together in a farmer-oriented platform.', tech: ['React', 'TypeScript', 'Machine Learning', 'APIs'], github: 'https://github.com/s7d4007/AgriSahayak', accent: 'blue' },
  { number: '03', title: 'Samvaad', type: 'REAL-TIME SYSTEMS', description: 'A focused chat experience for private conversations and connected communities.', detail: 'Real-time messaging, authentication, contact management, and database integration powered by Supabase.', tech: ['React', 'Supabase', 'Auth', 'WebSockets'], github: 'https://github.com/s7d4007/Samvaad', accent: 'orange' },
  { number: '04', title: 'Smart Exam Hall Monitoring', type: 'COMPUTER VISION / IOT', description: 'A modular monitoring system that connects vision, motion, and remote awareness.', detail: 'Real-time motion detection with OpenCV and ESP32-based IoT integration for exam hall monitoring.', tech: ['OpenCV', 'Computer Vision', 'ESP32', 'IoT'], github: 'https://github.com/s7d4007/Smart-Exam-Hall-Monitoring-System', accent: 'violet' },
]
export const experiments = ['PyQR', 'Authenticity', 'ProgrammerJokes', 'DiyaGlow-ESP32', 'Ask-Llama', 'VoxRead']
export const exploring = [['BUILDING', 'Generative AI', 'LLM Applications', 'APIs', 'Full-Stack Development'], ['EXPLORING', 'Agentic AI', 'Tool Calling', 'Context Engineering', 'AI Agents', 'NLP'], ['LEARNING', 'RAG', 'CAG', 'Backend Systems', 'Computer Vision']]
export const skills = { Languages: ['Python', 'SQL', 'C', 'C++', 'C#', 'JavaScript', 'TypeScript', 'Java'], 'Web / Frameworks': ['React.js', 'Next.js', 'React Native', 'ASP.NET Core MVC', 'Razor'], 'AI / ML': ['Generative AI', 'LLM Applications', 'Machine Learning', 'NLP', 'Computer Vision', 'OpenAI Whisper', 'Hugging Face Transformers', 'Ollama'], Databases: ['MySQL', 'PostgreSQL', 'Supabase'], Tools: ['Git', 'GitHub', 'Visual Studio', 'VS Code', 'APIs', 'WebSockets'], IoT: ['ESP32', 'PWM', 'IoT Systems'] }
export const leadership = [['TechKshetra', 'Coordinator · College Technology Club', 'Coordinating events, workshops, competitions, student initiatives, teams, volunteers, and event execution.'], ['COMPUTER SOCIETY OF INDIA', 'Coordinator · Mumbai Chapter, BKBCK', 'Technical initiatives, hackathons, workshops, student teams, faculty coordination, and event execution involving 500+ students.'], ['GEEKSFORGEEKS', 'Campus Mantri', 'Representing the campus community and encouraging participation in technical learning opportunities.'], ['Student Council', 'Council Member', 'Supporting student initiatives and contributing to a more connected campus experience.']]
export const journey = [['2024 — NOW', 'Technical experience', 'ShadowFox · Data Science Intern', 'Technical documentation and educational material around Python data visualization libraries including Matplotlib and Pandas.'], ['2024 — NOW', 'Technical experience', 'CodTech · Python Programming Intern', 'AI/NLP functionality, public APIs, predictive analysis, CSV report automation, and Python development.'], ['ONGOING', 'Community & leadership', 'TechKshetra · CSI · GeeksforGeeks · Student Council', 'Building spaces for students to learn, participate, collaborate, and ship ideas together.']]
export const socialLinks = { github: 'https://github.com/s7d4007', linkedin: 'https://www.linkedin.com/in/souvikdutta7', email: 'mailto:souvikdutta0718@gmail.com' }
